generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          permissions
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:  [name, description]
      filter:
        class: sfGuardPermissionFormFilter
        display:  [name, description, users_list, groups_list]
      form:    ~
      edit:    ~
      new:     ~
