prod:
  enabled: false
  level:   err
  rotate:  true
  purge:   false

#all:
#  enabled: true
#  level:   debug
#  rotate:  false
#  period:  7
#  history: 10
#  purge:   true
#  loggers:
#    sf_web_debug:
#      class: sfWebDebugLogger
#      param:
#        condition: %SF_WEB_DEBUG%
#    sf_file_debug:
#      class: sfFileLogger
#      param:
#        file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
