orm:
  slug: orm
  title: Object Relational Mapper
  short_title: ORM
  description: "Object relational mapper (ORM) for PHP 5.2.3+ and 5.3.0+ that sits on top of a powerful database abstraction layer (DBAL). One of its key features is the option to write database queries in a proprietary object oriented SQL dialect called Doctrine Query Language (DQL), inspired by Hibernates HQL. This provides developers with a powerful alternative to SQL that maintains flexibility without requiring unnecessary code duplication."
  latest_version: "1.2"
  is_primary: true
  versions:
    "1.2":
      git_checkout_command: git clone git://github.com/doctrine/doctrine1.git doctrine1
      svn_checkout_command: svn co http://svn.github.com/doctrine/doctrine1.git doctrine1
      api_source_path: source/orm1.2/lib
      stability: stable
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10031
      browse_source_link: http://github.com/doctrine/doctrine1
      documentation_items:
        api:
          slug: api
          title: API Documentation
          subtitle: Doctrine 1.2 ORM API Documentation
          description: Detailed API documentation for the Doctrine 1.2 codebase.
          route: "@project_api_documentation?slug=orm&version=1.2"
          icon: api_icon.png
          update_command: "rm -rf source/orm1.2 && git clone git://github.com/doctrine/doctrine1.git source/orm1.2 && rm -rf ../web/api/orm/1.2 && cd .. && php apidocs.php api-orm-1.2.ini"
        manual:
          slug: manual
          title: Doctrine ORM for PHP
          subtitle: Guide to Doctrine for PHP
          description: The Guide to Doctrine for PHP is the main source of documentation for the project. It is a reference book that can be read from start to finish and provides dozens of practice exercises that can be executed by the user.
          toc_path: documentation/orm1.2/manual
          markup_parser: text_wiki
          update_command: "rm -rf documentation/orm1.2 && git clone git://github.com/doctrine/doctrine1-documentation.git documentation/orm1.2"
          purchase_link: "http://www.amazon.com/Doctrine-ORM-PHP-Jonathan-Wage/dp/2918390038/ref=sr_1_1?ie=UTF8&s=books&qid=1246303098&sr=8-1"
          cover_image: "http://www.doctrine-project.org/uploads/assets/cover_images/16f6fbd99672319b4d4135d73f712f47ea586759.png"
          icon: reference_icon.png
        cookbook:
          slug: cookbook
          title: Doctrine Cookbook
          subtitle: Everyday recipes for everyday Doctrine users
          description: The cookbook is a collection of simple and advanced recipes for using Doctrine. They are both written by core Doctrine developers as well as by Doctrine users in the community.
          toc_path: documentation/orm1.2/cookbook
          markup_parser: text_wiki
          update_command: "rm -rf documentation/orm1.2 && git clone git://github.com/doctrine/doctrine1-documentation.git documentation/orm1.2"
          icon: cookbook_icon.png
      releases:
        "1.2.0":
          package_name: Doctrine-1.2.0.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/1.2.0
          pear_install_command: pear install pear.doctrine-project.org/Doctrine-1.2.0.tgz
        "1.2.1":
          package_name: Doctrine-1.2.1.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/1.2.1
          pear_install_command: pear install pear.doctrine-project.org/Doctrine-1.2.1.tgz
        "1.2.2":
          package_name: Doctrine-1.2.2.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/1.2.2
          pear_install_command: pear install pear.doctrine-project.org/Doctrine-1.2.2.tgz

    "2.0":
      api_source_path: source/orm2.0/lib/Doctrine/ORM
      git_checkout_command: git clone git://github.com/doctrine/doctrine2.git doctrine2
      svn_checkout_command: svn co http://svn.github.com/doctrine/doctrine2.git doctrine2
      stability: alpha
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10032
      browse_source_link: http://github.com/doctrine/doctrine2/tree/master/lib/Doctrine/ORM
      documentation_items:
        api:
          slug: api
          title: API Documentation
          subtitle: Doctrine 2.0 ORM API Documentation
          description: Detailed API documentation for the Doctrine 2.0 codebase.
          route: "@project_api_documentation?slug=orm&version=2.0"
          icon: api_icon.png
          update_command: "rm -rf source/orm2.0 && git clone git://github.com/doctrine/doctrine2.git source/orm2.0 && rm -rf ../web/api/orm/2.0 && cd .. && php apidocs.php api-orm-2.0.ini"
        reference:
          slug: reference
          title: Reference Documentation
          subtitle: Complete reference guide to Doctrine 2
          description: The Doctrine 2 Reference Documentation is the main source of documentation for the project. It is a reference book that can be read from start to finish and provides examples and information about the provided features.
          toc_path: documentation/orm2.0/manual
          markup_parser: markdown
          update_command: "rm -rf documentation/orm2.0 && git clone git://github.com/doctrine/orm-documentation.git documentation/orm2.0"
          icon: reference_icon.png
        cookbook:
          slug: cookbook
          title: Cookbook
          subtitle: Everyday recipes for everyday Doctrine users
          description: The cookbook is a collection of simple and advanced recipes for using Doctrine. They are both written by core Doctrine developers as well as by Doctrine users in the community.
          toc_path: documentation/orm2.0/cookbook
          markup_parser: markdown
          update_command: "rm -rf documentation/orm2.0 && git clone git://github.com/doctrine/orm-documentation.git documentation/orm2.0"
          icon: cookbook_icon.png
      releases:
        "2.0.0-ALPHA1":
          package_name: DoctrineORM-2.0.0-ALPHA1.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/2.0.0-ALPHA1
        "2.0.0-ALPHA2":
          package_name: DoctrineORM-2.0.0-ALPHA2.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/2.0.0-ALPHA2
        "2.0.0-ALPHA3":
          package_name: DoctrineORM-2.0.0-ALPHA3.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/2.0.0-ALPHA3
        "2.0.0-ALPHA4":
          package_name: DoctrineORM-2.0.0-ALPHA4.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/2.0.0-ALPHA4
        "2.0.0-BETA1":
          package_name: DoctrineORM-2.0.0-BETA1.tgz
          svn_checkout_command: svn co http://svn.doctrine-project.org/tags/2.0.0-BETA1

dbal:
  slug: dbal
  title: Database Abstraction Layer
  short_title: DBAL
  description: "Powerful database abstraction layer with many features for database schema introspection, schema management and PDO abstraction."
  latest_version: "2.0"
  is_primary: true
  versions:
    "2.0":
      stability: alpha
      git_checkout_command: git clone git://github.com/doctrine/doctrine2.git doctrine2
      svn_checkout_command: svn co http://svn.github.com/doctrine/doctrine2.git doctrine2
      api_source_path: source/orm2.0/lib/Doctrine/DBAL
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10040
      browse_source_link: http://github.com/doctrine/doctrine2/tree/master/lib/Doctrine/DBAL
      documentation_items:
        api:
          slug: api
          title: API Documentation
          subtitle: Doctrine 2.0 DBAL API Documentation
          description: Detailed API documentation for the Doctrine 2.0 DBAL.
          route: "@project_api_documentation?slug=dbal&version=2.0"
          icon: api_icon.png
          update_command: "rm -rf source/orm2.0 && git clone git://github.com/doctrine/doctrine2.git source/orm2.0 && rm -rf ../web/api/dbal/2.0 && cd .. && php apidocs.php api-dbal-2.0.ini"
        reference:
          slug: reference
          title: DBAL Reference Documentation
          subtitle: Reference for using the Doctrine Database Abstraction Layer
          description: Learn how to use the Doctrine Database Abstraction Layer and take advantage of all simple and advanced features.
          toc_path: documentation/dbal2.0/reference
          markup_parser: markdown
          update_command: "rm -rf documentation/dbal2.0 && git clone git://github.com/doctrine/dbal-documentation.git documentation/dbal2.0"
          icon: reference_icon.png

migrations:
  slug: migrations
  title: Database Migrations
  short_title: Migrations
  description: Easily migrate changes to your databases and version your schema with the Doctrine migrations library.
  latest_version: "2.0"
  is_primary: false
  versions:
    "2.0":
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10041
      browse_source_link: http://github.com/doctrine/migrations/tree/master/lib/Doctrine/DBAL/Migrations/
      stability: alpha
      git_checkout_command: git clone git://github.com/doctrine/migrations.git migrations
      svn_checkout_command: svn co http://svn.github.com/doctrine/migrations.git migrations
      api_source_path: source/migrations1.0/lib

rest:
  slug: rest
  title: "REST Server & Client"
  short_title: REST
  description: Doctrine REST Server for exposing Doctrine 2 entities as RESTful resources or even raw tables from any existing database using the DBAL.
  latest_version: "1.0"
  is_primary: false
  versions:
    "1.0":
      stability: alpha
      git_checkout_command: git clone git://github.com/doctrine/rest.git rest
      svn_checkout_command: svn co http://svn.github.com/doctrine/rest.git rest
      api_source_path: source/rest1.0/lib
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10042
      browse_source_link: http://github.com/doctrine/rest/tree/master/lib/Doctrine/REST/
      documentation_items:
        api:
          slug: api
          title: API Documentation
          subtitle: "Doctrine REST Server & Client API Documentation"
          description: "Detailed API documentation for the Doctrine REST Server & Client 1.0".
          route: "@project_api_documentation?slug=rest&version=1.0"
          icon: api_icon.png
          update_command: "rm -rf source/rest1.0 && git clone git://github.com/doctrine/rest.git source/rest1.0 && rm -rf ../web/api/rest/1.0 && cd .. && php apidocs.php api-rest-1.0.ini"
        reference:
          slug: reference
          title: "REST Server & Client Documentation"
          subtitle: Reference for using the Doctrine REST Server and Client
          description: Learn how to use the Doctrine REST Server and Client to easily build web services.
          toc_path: documentation/rest1.0/reference
          markup_parser: markdown
          update_command: "rm -rf documentation/rest1.0 && git clone git://github.com/doctrine/rest-documentation.git documentation/rest1.0"
          icon: reference_icon.png

mongodb_odm:
  slug: mongodb_odm
  title: "MongoDB Object Document Mapper"
  short_title: MongoDBODM
  description: The Doctrine MongoDB Object Document Mapper is a fully featured library for persisting PHP 5 objects to MongoDB much in the same way the Doctrine 2 ORM works.
  latest_version: "1.0"
  is_primary: false
  namespace: Doctrine\ODM\MongoDB
  versions:
    "1.0":
      stability: alpha
      git_checkout_command: git clone git://github.com/jwage/odm.git mongodb_odm
      svn_checkout_command: svn co http://svn.github.com/jwage/odm.git mongodb_odm
      api_source_path: source/mongodb_odm1.0/lib
      issues_link: http://www.doctrine-project.org/jira/secure/project/ViewProject.jspa?pid=10044
      browse_source_link: http://github.com/jwage/odm
      documentation_items:
        api:
          slug: api
          title: API Documentation
          subtitle: "Doctrine MongoDB Object Document Mapper API Documentation"
          description: "Detailed API documentation for the Doctrine MongoDB Object Document Mapper".
          route: "@project_api_documentation?slug=mongodb_odm&version=1.0"
          icon: api_icon.png
          update_command: "rm -rf source/mongodb_odm1.0 && git clone git://github.com/jwage/odm.git source/mongodb_odm1.0 && rm -rf ../web/api/mongodb_odm/1.0 && cd .. && php apidocs.php api-mongodb_odm-1.0.ini"
        reference:
          slug: reference
          title: "Doctrine MongoDB Object Document Mapper Reference Documentation"
          subtitle: Reference for using the Doctrine MongoDB Object Document Mapper
          description: Learn how to use the Doctrine MongoDB Object Document Mapper quickly and easily.
          toc_path: documentation/odm1.0/MongoDB
          markup_parser: markdown
          update_command: "rm -rf documentation/odm1.0 && git clone git://github.com/jwage/odm-documentation.git documentation/odm1.0"
          icon: reference_icon.png