---
Contributor:
  actAs:
    Sluggable:
      fields: [name]
    Timestampable:
  columns: 
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
    nick:
      type: string(255)
    role:
      type: string(255)
    email:
      type: string(255)
    about:
      type: clob
    core:
      type: boolean
      default: false
    active:
      type: boolean
      default: true